module.exports = {
    LESSON_COMPLETED: 5,
    INSTRUCTION_GRADED: {
        BELOW_70: 10,
        FROM_70: 15,
        FROM_90: 20,
        PERFECT: 25,
    },
    DAILY_STREAK_PER_DAY: [0, 0, 1, 2, 3, 4, 5],
    DAILY_STREAK_CAP_DAY: 7,
    STREAK_BONUS_7: 10,
    STREAK_BONUS_30: 50,
    MODULE_COMPLETED: 30,
    PROGRAM_COMPLETED: 100,
    FAVORITE_RECEIVED: 2,
    STORE: {
        MYSTERY_BOX: 400,
        RETRY_INSTRUCTION: 200,
        STREAK_SHIELD: 25,
        STREAK_RECOVERY: 30,
    },
    STREAK_SHIELD_MAX: 1,
    STREAK_RECOVERY_WINDOW_MS: 24 * 60 * 60 * 1000,
};
