const covers = [
    {
        id: 'default',
        name: 'Clásica',
        description: 'La portada original de STANNUM Game.',
        price: 0,
        rarity: 'common',
        imageKey: 'cover_default',
    },
    {
        id: 'horizon',
        name: 'Horizonte',
        description: 'Un atardecer que marca el comienzo de algo grande.',
        price: 200,
        rarity: 'uncommon',
        imageKey: 'cover_horizon',
    },
    {
        id: 'synthwave',
        name: 'Synthwave',
        description: 'Un paisaje retro con luces de neón hacia el horizonte.',
        price: 200,
        rarity: 'uncommon',
        imageKey: 'cover_synthwave',
    },
    {
        id: 'arena',
        name: 'Escenario',
        description: 'Un escenario masivo frente a miles de personas.',
        price: 250,
        rarity: 'uncommon',
        imageKey: 'cover_arena',
    },
    {
        id: 'rugby',
        name: 'Trinchera',
        description: 'La intensidad del rugby bajo las luces de neón.',
        price: 400,
        rarity: 'rare',
        imageKey: 'cover_rugby',
    },
    {
        id: 'pit_lane',
        name: 'Pit Lane',
        description: 'Un F1 esperando en boxes bajo la oscuridad de la noche.',
        price: 450,
        rarity: 'rare',
        imageKey: 'cover_pit_lane',
    },
    {
        id: 'golden_boot',
        name: 'Botín Dorado',
        description: 'El impacto perfecto entre el botín y la pelota.',
        price: 700,
        rarity: 'epic',
        imageKey: 'cover_golden_boot',
    },
    {
        id: 'velocity',
        name: 'Velocidad',
        description: 'Un F1 a máxima velocidad dejando chispas a su paso.',
        price: 750,
        rarity: 'epic',
        imageKey: 'cover_velocity',
    },
    {
        id: 'void_throne',
        name: 'Trono',
        description: 'Un trono oscuro flotando en el vacío del cosmos.',
        price: 800,
        rarity: 'epic',
        imageKey: 'cover_void_throne',
    },
    {
        id: 'summer_2026',
        name: 'Summer 2026',
        description: 'Edición coleccionable del verano 2026.',
        price: 1000,
        rarity: 'legendary',
        imageKey: 'cover_summer_2026',
    },
    {
        id: 'podium',
        name: 'Podio',
        description: 'De pie en lo más alto, rodeado de confetti dorado.',
        price: 1200,
        rarity: 'legendary',
        imageKey: 'cover_podium',
    },
    {
        id: 'victory',
        name: 'Victoria',
        description: 'El momento de levantar el trofeo bajo los fuegos artificiales.',
        price: 1500,
        rarity: 'legendary',
        imageKey: 'cover_victory',
    },
];

const coversMap = Object.fromEntries(covers.map(c => [c.id, c]));

module.exports = { covers, coversMap };
